name: "default action"

on:
  push:
    branches: ["main", '*']
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v5
    - name: Configure Python
      uses: actions/setup-python@v6
      with: ${{ matrix.python-version }}
    - name: Install Python dependencies
      run: pip install -r requirements.txt
    - name: Run tests
      run: coverage run -m pytest -v -s
    - name: Generate test coverage report
      run: coverage report -m
